# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
## 解释：http://blog.csdn.net/willxue123/article/details/50994852

# Site
title: Pimi's Blog
subtitle: A lazy youth, a lousy age.
description: 天道酬勤，上善若水
author: Pimi Chen
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://pimichen.com/blog
root: /blog/
# permalink: :year/:month/:day/:title/
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1 # 转换文件名，1代表小写；2代表大写；默认为0，意思就是创建文章的时候，是否自动帮你转换文件名，默认就行，意义不大。
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: baidu_url_submitter
  repo:
- type: git
  repo:
    github: git@github.com:cpm828/blog.git # cpm828.github.io/blog
    # coding: git@git.coding.net:pimi/pimi.coding.me.git # pimi.coding.me 
  branch: master


# search
# algolia search
algolia:
  applicationID: '7U5GLOOLPQ'
  apiKey: '217b43ed2d3cb495895c71b272d78d13'
  adminApiKey: '1db38e90c6109949dff16372208a19c3'
  indexName: 'pimi_blog'
  chunkSize: 5000

# local search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000


# 设置页面的文章篇数
index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

# 百度推送
baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: pimichen.com # 在百度站长平台中注册的域名
  token: GeeAEOp1scRIOxys # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里

# 百度站长平台
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# pwa
pwa:
  manifest:
    path: /blog/manifest.json
    body:
      name: Pimi's Blog
      short_name: Pimi Blog
      theme_color: white
      background_color: white
      display: standalone
      orientation: portrait
      scope: /
      start_url: /
      icons:
        - src: /blog/images/public/16.png
          type: image/png
          sizes: 16x16
        - src: /blog/images/public/32.png
          type: image/png
          sizes: 32x32
        - src: /blog/images/public/36.png
          type: image/png
          sizes: 36x36
        - src: /blog/images/public/48.png
          type: image/png
          sizes: 48x48
        - src: /blog/images/public/72.png
          type: image/png
          sizes: 72x72
        - src: /blog/images/public/96.png
          type: image/png
          sizes: 96x96
        - src: /blog/images/public/144.png
          type: image/png
          sizes: 144x144
        - src: /blog/images/public/192.png
          type: image/png
          sizes: 192x192
        - src: /blog/images/public/512.png
          type: image/png
          sizes: 512x512
        - src: /blog/images/public/apple-touch-icon.png
          type: image/png
          sizes: 180x180
  serviceWorker:
    path: /blog/sw.js
    preload:
      urls:
        - /
      posts: 12
    opts:
      networkTimeoutSeconds: 30
    routes:
      - pattern: !!js/regexp /hm.baidu.com/
        strategy: networkOnly
      - pattern: !!js/regexp /www.google-analytics.com/
        strategy: networkOnly
      - pattern: !!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/
        strategy: cacheFirst
      - pattern: !!js/regexp /\//
        strategy: networkFirst
  priority: 5